import type { Metadata } from 'next'
import './globals.css'
import './style.css'
import GoogleAnalytics from '@/components/lib/GoogleAnalytics'
import ReduxProvider from '@/components/lib/ReduxProvider'

const siteName = "Create Next App";
const desc = "Generated by create next app"
const url = "http://localhost:3000"

export const metadata: Metadata = {
  metadataBase: new URL(url),
  title: siteName,
  description: desc,
  viewport: 'width=device-width, initial-scale=1',
  openGraph: {
    title: siteName,
    description: desc,
    url: url,
    siteName: siteName,
    locale: "ja_JP",
    type: "website"
  },
  twitter: {
    title: siteName,
    description: desc,
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <head>
        {/* <GoogleAnalytics/> */}
      </head>
      <body>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
